//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class altas
    {
        public int idalta { get; set; }
        public int idinternado { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
    
        public virtual internados internados { get; set; }
    }
}
