//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class camillas
    {
        public camillas()
        {
            this.internados = new HashSet<internados>();
        }
    
        public int idcamilla { get; set; }
        public int idhabitacion { get; set; }
        public int numero_camilla { get; set; }
        public string estado { get; set; }
    
        public virtual habitaciones habitaciones { get; set; }
        public virtual ICollection<internados> internados { get; set; }
    }
}
