//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public consulta()
        {
            this.diagnostico = new HashSet<diagnostico>();
            this.expediente = new HashSet<expediente>();
            this.medicamentosrecetados = new HashSet<medicamentosrecetados>();
            this.pacientesintomas = new HashSet<pacientesintomas>();
        }
    
        public int idconsulta { get; set; }
        public int idmedico { get; set; }
        public int idpaciente { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual medicos medicos { get; set; }
        public virtual pacientes pacientes { get; set; }
        public virtual ICollection<diagnostico> diagnostico { get; set; }
        public virtual ICollection<expediente> expediente { get; set; }
        public virtual ICollection<medicamentosrecetados> medicamentosrecetados { get; set; }
        public virtual ICollection<pacientesintomas> pacientesintomas { get; set; }
    }
}
