//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamentos
    {
        public departamentos()
        {
            this.empleados = new HashSet<empleados>();
            this.municipios = new HashSet<municipios>();
            this.pacientes = new HashSet<pacientes>();
        }
    
        public int id_departamento { get; set; }
        public string nombredepartamento { get; set; }
    
        public virtual ICollection<empleados> empleados { get; set; }
        public virtual ICollection<municipios> municipios { get; set; }
        public virtual ICollection<pacientes> pacientes { get; set; }
    }
}
