//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallemedicamentos_recetados
    {
        public detallemedicamentos_recetados()
        {
            this.medicamentosrecetados = new HashSet<medicamentosrecetados>();
        }
    
        public int id_detalle { get; set; }
        public int cantidadrecetada { get; set; }
        public string dosis { get; set; }
        public int idIM { get; set; }
    
        public virtual ICollection<medicamentosrecetados> medicamentosrecetados { get; set; }
    }
}
