//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public empleados()
        {
            this.encargados_de_laboratorio = new HashSet<encargados_de_laboratorio>();
            this.encargadosdefarmacia = new HashSet<encargadosdefarmacia>();
            this.horariosempleados = new HashSet<horariosempleados>();
            this.medicos = new HashSet<medicos>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int idempleado { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int iddepartamento { get; set; }
        public int idmunicipio { get; set; }
        public string dui { get; set; }
        public string NIT { get; set; }
        public int idcargo { get; set; }
        public string estado { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha_contratacion { get; set; }
        public string telefono { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual municipios municipios { get; set; }
        public virtual ICollection<encargados_de_laboratorio> encargados_de_laboratorio { get; set; }
        public virtual ICollection<encargadosdefarmacia> encargadosdefarmacia { get; set; }
        public virtual ICollection<horariosempleados> horariosempleados { get; set; }
        public virtual ICollection<medicos> medicos { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
