//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class encargados_de_laboratorio
    {
        public encargados_de_laboratorio()
        {
            this.examenes = new HashSet<examenes>();
        }
    
        public int idencargado { get; set; }
        public int idempleado { get; set; }
        public int JVPLC { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual ICollection<examenes> examenes { get; set; }
    }
}
