//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class enfermedades
    {
        public enfermedades()
        {
            this.diagnostico = new HashSet<diagnostico>();
            this.fallecidos = new HashSet<fallecidos>();
        }
    
        public int idenfermedad { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
    
        public virtual ICollection<diagnostico> diagnostico { get; set; }
        public virtual ICollection<fallecidos> fallecidos { get; set; }
    }
}
