//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class examenes
    {
        public int idexamenes { get; set; }
        public int idsubcategoriaexamen { get; set; }
        public string resultadoanalisis { get; set; }
        public string estado { get; set; }
        public int idencargadolaboratorio { get; set; }
    
        public virtual encargados_de_laboratorio encargados_de_laboratorio { get; set; }
        public virtual subcategoria_examen subcategoria_examen { get; set; }
    }
}
