//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class examenespendientes
    {
        public int idexamen { get; set; }
        public int idsubcategoria { get; set; }
        public bool estado { get; set; }
        public int idconsulta { get; set; }
    
        public virtual subcategoria_examen subcategoria_examen { get; set; }
    }
}
