//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class expediente
    {
        public int idexpediente { get; set; }
        public int idpaciente { get; set; }
        public int idconsulta { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual consulta consulta { get; set; }
        public virtual pacientes pacientes { get; set; }
    }
}
