//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitaciones
    {
        public habitaciones()
        {
            this.camillas = new HashSet<camillas>();
        }
    
        public int idhabitacion { get; set; }
        public int numplanta { get; set; }
        public int numero_de_habitacion { get; set; }
    
        public virtual ICollection<camillas> camillas { get; set; }
    }
}
