//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class internados
    {
        public internados()
        {
            this.altas = new HashSet<altas>();
        }
    
        public int idinternado { get; set; }
        public int idpaciente { get; set; }
        public Nullable<System.DateTime> fecha_de_ingreso { get; set; }
        public int idcamilla { get; set; }
        public string diagnostico { get; set; }
    
        public virtual ICollection<altas> altas { get; set; }
        public virtual camillas camillas { get; set; }
        public virtual pacientes pacientes { get; set; }
    }
}
