//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioMedicamentos
    {
        public int idInventario { get; set; }
        public System.DateTime fechaCaducidad { get; set; }
        public string CodLote { get; set; }
        public int idproveedor { get; set; }
        public int idmedicamento { get; set; }
        public int stock { get; set; }
    
        public virtual Medicamentos Medicamentos { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
