//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_medicamentos
    {
        public int idIM { get; set; }
        public string nombreMedicamento { get; set; }
        public int idlaboratorio { get; set; }
        public int idlote { get; set; }
        public Nullable<int> cantidad_concentracion { get; set; }
        public int idpresentacion { get; set; }
        public int idunidad { get; set; }
        public int cantidad_unidad { get; set; }
    
        public virtual laboratorios_farmaceuticos laboratorios_farmaceuticos { get; set; }
        public virtual Lote_Medicamentos Lote_Medicamentos { get; set; }
        public virtual presentacionmedicamento presentacionmedicamento { get; set; }
        public virtual unidades unidades { get; set; }
    }
}
