//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        public Medicamentos()
        {
            this.InventarioMedicamentos = new HashSet<InventarioMedicamentos>();
        }
    
        public int idmedicamento { get; set; }
        public string nombreMedicamento { get; set; }
        public string presentacion { get; set; }
    
        public virtual ICollection<InventarioMedicamentos> InventarioMedicamentos { get; set; }
    }
}
