//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicos
    {
        public medicos()
        {
            this.consulta = new HashSet<consulta>();
            this.quirofano = new HashSet<quirofano>();
        }
    
        public int idmedico { get; set; }
        public int idempleado { get; set; }
        public string JVPM { get; set; }
        public int id_arealaboral { get; set; }
        public int idespecialidad { get; set; }
    
        public virtual area_Laboral area_Laboral { get; set; }
        public virtual ICollection<consulta> consulta { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual especialidadmedicos especialidadmedicos { get; set; }
        public virtual ICollection<quirofano> quirofano { get; set; }
    }
}
