//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamentosrecetados
    {
        public int idmedicamentorecetado { get; set; }
        public int idconsulta { get; set; }
        public int id_detalle { get; set; }
    
        public virtual consulta consulta { get; set; }
        public virtual detallemedicamentos_recetados detallemedicamentos_recetados { get; set; }
    }
}
