//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hospitalEntities : DbContext
    {
        public hospitalEntities()
            : base("name=hospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<altas> altas { get; set; }
        public DbSet<area_Laboral> area_Laboral { get; set; }
        public DbSet<camillas> camillas { get; set; }
        public DbSet<cargos> cargos { get; set; }
        public DbSet<categoria_examen> categoria_examen { get; set; }
        public DbSet<cita> cita { get; set; }
        public DbSet<consulta> consulta { get; set; }
        public DbSet<departamentos> departamentos { get; set; }
        public DbSet<detallemedicamentos_recetados> detallemedicamentos_recetados { get; set; }
        public DbSet<DetallePedido> DetallePedido { get; set; }
        public DbSet<diagnostico> diagnostico { get; set; }
        public DbSet<empleados> empleados { get; set; }
        public DbSet<encargados_de_laboratorio> encargados_de_laboratorio { get; set; }
        public DbSet<encargadosdefarmacia> encargadosdefarmacia { get; set; }
        public DbSet<enfermedades> enfermedades { get; set; }
        public DbSet<especialidadmedicos> especialidadmedicos { get; set; }
        public DbSet<estadoDelPedido> estadoDelPedido { get; set; }
        public DbSet<examenes> examenes { get; set; }
        public DbSet<examenespendientes> examenespendientes { get; set; }
        public DbSet<expediente> expediente { get; set; }
        public DbSet<fallecidos> fallecidos { get; set; }
        public DbSet<habitaciones> habitaciones { get; set; }
        public DbSet<horariosempleados> horariosempleados { get; set; }
        public DbSet<internados> internados { get; set; }
        public DbSet<inventario_medicamentos> inventario_medicamentos { get; set; }
        public DbSet<InventarioMedicamentos> InventarioMedicamentos { get; set; }
        public DbSet<laboratorios_farmaceuticos> laboratorios_farmaceuticos { get; set; }
        public DbSet<Lote_Medicamentos> Lote_Medicamentos { get; set; }
        public DbSet<Medicamentos> Medicamentos { get; set; }
        public DbSet<medicamentosrecetados> medicamentosrecetados { get; set; }
        public DbSet<medicos> medicos { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<municipios> municipios { get; set; }
        public DbSet<pacientes> pacientes { get; set; }
        public DbSet<pacientesintomas> pacientesintomas { get; set; }
        public DbSet<pedidoMedicamento> pedidoMedicamento { get; set; }
        public DbSet<presentacionmedicamento> presentacionmedicamento { get; set; }
        public DbSet<proveedores> proveedores { get; set; }
        public DbSet<quirofano> quirofano { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<sintomas> sintomas { get; set; }
        public DbSet<sinversion> sinversion { get; set; }
        public DbSet<subcategoria_examen> subcategoria_examen { get; set; }
        public DbSet<tipo_operaciones> tipo_operaciones { get; set; }
        public DbSet<unidades> unidades { get; set; }
        public DbSet<usuariomenu> usuariomenu { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<viaAdministracion> viaAdministracion { get; set; }
    }
}
