//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacientesintomas
    {
        public int idpacientesientomas { get; set; }
        public Nullable<int> idconsulta { get; set; }
        public Nullable<int> idsintoma { get; set; }
    
        public virtual consulta consulta { get; set; }
        public virtual sintomas sintomas { get; set; }
    }
}
