//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacientes
    {
        public pacientes()
        {
            this.cita = new HashSet<cita>();
            this.consulta = new HashSet<consulta>();
            this.expediente = new HashSet<expediente>();
            this.fallecidos = new HashSet<fallecidos>();
            this.internados = new HashSet<internados>();
            this.quirofano = new HashSet<quirofano>();
        }
    
        public int idpaciente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int id_departamento { get; set; }
        public int id_municipio { get; set; }
        public string telefono { get; set; }
        public string genero { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string nombreencargado { get; set; }
        public string apellidoencargado { get; set; }
        public string duiencargado { get; set; }
        public string telefono_encargado { get; set; }
        public string direccion { get; set; }
        public string dui { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
        public virtual ICollection<consulta> consulta { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual ICollection<expediente> expediente { get; set; }
        public virtual ICollection<fallecidos> fallecidos { get; set; }
        public virtual ICollection<internados> internados { get; set; }
        public virtual municipios municipios { get; set; }
        public virtual ICollection<quirofano> quirofano { get; set; }
    }
}
