//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoMedicamento
    {
        public pedidoMedicamento()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
        }
    
        public int idPedidoMedicamento { get; set; }
        public int idproveedor { get; set; }
        public System.DateTime fechaPedido { get; set; }
    
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
