//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class quirofano
    {
        public int idquirofano { get; set; }
        public string operacion_realizada { get; set; }
        public int idmedico { get; set; }
        public int idpaciente { get; set; }
        public string observaciones { get; set; }
        public int idtipo_operacion { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual medicos medicos { get; set; }
        public virtual pacientes pacientes { get; set; }
        public virtual tipo_operaciones tipo_operaciones { get; set; }
    }
}
