//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.usuariomenu = new HashSet<usuariomenu>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int idrol { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<usuariomenu> usuariomenu { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
