//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategoria_examen
    {
        public subcategoria_examen()
        {
            this.examenes = new HashSet<examenes>();
            this.examenespendientes = new HashSet<examenespendientes>();
        }
    
        public int idsubcategoria_examen { get; set; }
        public string nombresubcategoria { get; set; }
        public int idcategoria { get; set; }
        public string descripcion { get; set; }
    
        public virtual categoria_examen categoria_examen { get; set; }
        public virtual ICollection<examenes> examenes { get; set; }
        public virtual ICollection<examenespendientes> examenespendientes { get; set; }
    }
}
