//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_operaciones
    {
        public tipo_operaciones()
        {
            this.quirofano = new HashSet<quirofano>();
        }
    
        public int idtipo_operaciones { get; set; }
        public string tipo_operacion { get; set; }
        public string observaciones { get; set; }
    
        public virtual ICollection<quirofano> quirofano { get; set; }
    }
}
