//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidades
    {
        public unidades()
        {
            this.inventario_medicamentos = new HashSet<inventario_medicamentos>();
            this.presentacionmedicamento = new HashSet<presentacionmedicamento>();
        }
    
        public int idunidad { get; set; }
        public string unidad { get; set; }
    
        public virtual ICollection<inventario_medicamentos> inventario_medicamentos { get; set; }
        public virtual ICollection<presentacionmedicamento> presentacionmedicamento { get; set; }
    }
}
