//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string idusuario { get; set; }
        public string clave { get; set; }
        public int idrol { get; set; }
        public int idempleado { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual roles roles { get; set; }
    }
}
